version: '3'
services:
  ynabcache:

    build:
      context: ./service.ynabCache


    ports: 
      - "8080"

    networks:
      - backend

    deploy:
      replicas: 1

    env_file:
      - ./service.ynabCache/.env

  dailyspend:
    
    build:
      context: ./service.dailySpend

    ports:
      - "8081"

    expose:
      - "8081"

    networks:
      - backend
    deploy:
      replicas: 1

    restart: always

networks:
  backend:

